import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@cometchat/chat-uikit-react': new URL('./src', import.meta.url).pathname,
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.spec.{ts,tsx}', 'src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.spec.{ts,tsx}',
        'src/**/*.test.{ts,tsx}',
        'src/**/*.stories.{ts,tsx}',
        'src/**/*.e2e.{ts,tsx}',
        'src/**/index.ts',
        'src/testing/**',
        'src/components/base/CometChatEmojiKeyboard/CometChatEmojiData.ts',
        'src/constants/Enums.ts',
        'src/**/*.types.ts',
        'src/assets/**',
        'src/fonts/**',
        'src/styles/**',
        'src/resources/**',
        'src/components/CometChatAudioBubble/wavesurfer/**',
        'src/plugins/ai/**',
        'src/components/**/use*.ts',
        'src/components/**/*Manager.ts',
        'src/components/**/*Root.tsx',
        'src/hooks/useOngoingCall.ts',
        'src/utils/RichTextEditor/useRichTextEditor.ts',
        'src/utils/RichTextEditor/RichTextEditor.ts',
        'src/utils/RichTextEditor/formats/ListFormat.ts',
        'src/utils/RichTextEditor/formats/CodeBlockFormat.ts',
        'src/utils/RichTextEditor/formats/InlineCodeFormat.ts',
        'src/utils/RichTextEditor/markdown/AutoListDetector.ts',
        'src/plugins/core/call-action/CometChatCallActionPlugin.ts',
        'src/plugins/core/call-action/CometChatMeetingPlugin.ts',
        'src/utils/RichTextEditor/formats/LinkFormat.ts',
        'src/utils/RichTextEditor/mentions/MentionManager.ts',
        'src/components/CometChatSearch/CometChatSearchMessagesList.tsx',
        'src/components/CometChatSearch/CometChatSearchConversationsList.tsx',
        'src/components/CometChatMessageComposer/CometChatMessageComposer*.tsx',
        'src/components/CometChatGroupMembers/CometChatGroupMembers.tsx',
        'src/components/CometChatGroupMembers/CometChatGroupMembersItem.tsx',
        'src/components/CometChatReactionList/CometChatReactionListItems.tsx',
        'src/components/CometChatReactionList/CometChatReactionListTabs.tsx',
        'src/components/CometChatNotificationFeed/CometChatNotificationFeedItem.tsx',
        'src/components/CometChatNotificationFeed/CometChatNotificationFeed.tsx',
        'src/components/CometChatMessageBubble/CometChatMessageReplyPreview.tsx',
        'src/components/CometChatReactions/CometChatReactionsList.tsx',
        'src/components/CometChatMessageList/CometChatMessageListAIFooter.tsx',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 75,
        statements: 80,
      },
    },
  },
});
